const defaultItems = [
  {id:1,name:'Sewa gedung kegiatan',category:'Acara & Seremoni',volume:1,unit:'hari',price:12500000,status:'Lunas',note:'Gedung Pemuda Nusantara'},
  {id:2,name:'Sound system dan panggung',category:'Perlengkapan',volume:1,unit:'paket',price:8500000,status:'DP',note:'Termasuk operator'},
  {id:3,name:'Konsumsi peserta',category:'Konsumsi',volume:350,unit:'kotak',price:35000,status:'Belum dibayar',note:'Makan siang dan snack'},
  {id:4,name:'Dekorasi dan backdrop',category:'Dekorasi',volume:1,unit:'paket',price:6750000,status:'Lunas',note:'Tema merah putih'},
  {id:5,name:'Dokumentasi foto & video',category:'Dokumentasi',volume:1,unit:'paket',price:5500000,status:'DP',note:'Dokumentasi selama acara'},
  {id:6,name:'Publikasi dan desain',category:'Publikasi',volume:1,unit:'paket',price:3800000,status:'Lunas',note:'Poster, spanduk, dan media sosial'},
  {id:7,name:'Honor panitia dan MC',category:'Honorarium',volume:8,unit:'orang',price:450000,status:'Belum dibayar',note:'Apresiasi panitia'},
  {id:8,name:'Transportasi dan operasional',category:'Transportasi',volume:1,unit:'paket',price:4200000,status:'Belum dibayar',note:'Mobilisasi perlengkapan'},
  {id:9,name:'Keamanan & kebersihan',category:'Keamanan',volume:1,unit:'paket',price:2900000,status:'Lunas',note:'Petugas keamanan dan kebersihan'}
];
const categories = ['Acara & Seremoni','Perlengkapan','Konsumsi','Dekorasi','Dokumentasi','Publikasi','Honorarium','Transportasi','Keamanan'];
let items = JSON.parse(localStorage.getItem('sumpahPemudaBudget') || 'null') || defaultItems;
const rupiah = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const $ = id => document.getElementById(id);
function save(){localStorage.setItem('sumpahPemudaBudget',JSON.stringify(items));}
function total(item){return item.volume * item.price;}
function render(){
  const totalBudget=items.reduce((s,i)=>s+total(i),0); const spent=items.filter(i=>i.status!=='Belum dibayar').reduce((s,i)=>s+total(i),0); const remaining=totalBudget-spent; const percent=totalBudget?Math.round(spent/totalBudget*100):0;
  $('totalBudget').textContent=rupiah(totalBudget);$('totalSpent').textContent=rupiah(spent);$('totalRemaining').textContent=rupiah(remaining);$('spentPercent').textContent=percent+'%';$('remainingPercent').textContent=(100-percent)+'%';$('overallProgress').style.width=Math.min(percent,100)+'%';$('donutPercent').textContent=percent+'%';
  renderFilters(); renderTable(); renderCategories(); renderChart();
}
function renderFilters(){const selected=$('categoryFilter').value; $('categoryFilter').innerHTML='<option value="all">Semua kategori</option>'+categories.map(c=>`<option ${c===selected?'selected':''}>${c}</option>`).join(''); $('itemCategory').innerHTML=categories.map(c=>`<option>${c}</option>`).join('');}
function renderTable(){const query=$('searchInput').value.toLowerCase();const cat=$('categoryFilter').value;const status=$('statusFilter').value;const filtered=items.filter(i=>(i.name.toLowerCase().includes(query)||i.category.toLowerCase().includes(query))&&(cat==='all'||i.category===cat)&&(status==='all'||i.status===status));$('budgetTable').innerHTML=filtered.length?filtered.map(i=>`<tr><td>${i.name}<small>${i.note||''}</small></td><td class="category-label">${i.category}</td><td>${i.volume} ${i.unit}</td><td>${rupiah(i.price)}</td><td>${rupiah(total(i))}</td><td><span class="status ${i.status==='Lunas'?'lunas':i.status==='DP'?'dp':'belum'}">${i.status}</span></td><td><button class="row-action" onclick="editItem(${i.id})" aria-label="Edit">⋮</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Tidak ada data yang cocok.</td></tr>';$('tableCount').textContent=`Menampilkan ${filtered.length} dari ${items.length} item`}
function renderCategories(){const totals={};categories.forEach(c=>totals[c]=items.filter(i=>i.category===c).reduce((s,i)=>s+total(i),0));const sorted=Object.entries(totals).filter(([,v])=>v).sort((a,b)=>b[1]-a[1]);const colors=['#3569ee','#f28b39','#21ad77','#8b68dc','#e15d79'];$('categoryLegend').innerHTML=sorted.slice(0,5).map(([name,val],n)=>`<div class="legend-row"><i style="background:${colors[n]}"></i><span>${name}</span><b>${Math.round(val/(Object.values(totals).reduce((a,b)=>a+b,0)||1)*100)}%</b></div>`).join('');}
function renderChart(){const monthly=[0,0,0,0,0,0,0,0,0,0,0,0];items.forEach(i=>monthly[i.id%12]+=total(i));const max=Math.max(...monthly,60000000);$('chartBars').innerHTML=monthly.map((v,n)=>`<div class="bar-pair"><i class="bar budget" style="height:${Math.max(8,v/max*100)}%"></i><i class="bar realization" style="height:${Math.max(4,v/max*(n<9?.68:.35)*100)}%"></i></div>`).join('');}
function openModal(item=null){$('modalBackdrop').classList.add('show');$('modalTitle').textContent=item?'Edit anggaran':'Tambah anggaran';$('editId').value=item?.id||'';$('itemName').value=item?.name||'';$('itemCategory').value=item?.category||categories[0];$('itemStatus').value=item?.status||'Belum dibayar';$('itemVolume').value=item?.volume||1;$('itemUnit').value=item?.unit||'paket';$('itemPrice').value=item?.price||'';$('itemNote').value=item?.note||'';$('itemName').focus()}
function closeModal(){$('modalBackdrop').classList.remove('show')}
window.editItem=id=>openModal(items.find(i=>i.id===id));
$('budgetForm').addEventListener('submit',e=>{e.preventDefault();const id=Number($('editId').value);const data={id:id||Date.now(),name:$('itemName').value,category:$('itemCategory').value,status:$('itemStatus').value,volume:Number($('itemVolume').value),unit:$('itemUnit').value,price:Number($('itemPrice').value),note:$('itemNote').value};if(id)items=items.map(i=>i.id===id?data:i);else items.push(data);save();render();closeModal();showToast(id?'Anggaran berhasil diperbarui':'Anggaran baru berhasil ditambahkan')});
['addTopBtn','addTableBtn'].forEach(id=>$(id).addEventListener('click',()=>openModal()));['closeModal','cancelModal'].forEach(id=>$(id).addEventListener('click',closeModal));$('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});['searchInput','categoryFilter','statusFilter'].forEach(id=>$(id).addEventListener('input',renderTable));$('resetFilter').addEventListener('click',()=>{$('searchInput').value='';$('categoryFilter').value='all';$('statusFilter').value='all';renderTable()});$('printBtn').addEventListener('click',()=>window.print());$('reportBtn').addEventListener('click',()=>showToast('Laporan pertanggungjawaban siap dicetak'));$('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('darkMode',document.body.classList.contains('dark'))});if(localStorage.getItem('darkMode')==='true')document.body.classList.add('dark');$('menuToggle').addEventListener('click',()=>$('sidebar').classList.toggle('open'));function showToast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}render();
